export const SET_SEARCH_SETTINGS = "SET_SEARCH_SETTINGS";
export const LOAD_MASTER_DATA_REQUESTED = "LOAD_MASTER_DATA_REQUESTED"
export const LOAD_MASTER_DATA_SUCCEEDED = "LOAD_MASTER_DATA_SUCCEEDED"
export const LOAD_MASTER_DATA_FAILED = "LOAD_MASTER_DATA_FAILED"
